#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER


/** @brief 由中断回调函数切换的外部中断标志 */
static volatile bool s_ext_irq_flag = false;

/**
 * @brief 外部中断 IRQ4 回调函数
 *
 * 当 ICU 外部中断发生时调用，切换外部中断标志。
 *
 * @param[in] p_args 中断回调参数（未使用）
 */
void external_irq4_callback(external_irq_callback_args_t *p_args)
{
    (void)p_args;
    s_ext_irq_flag = !s_ext_irq_flag;
}

/**
 * @brief 初始化外部中断 IRQ4
 *
 * 打开并使能 ICU 外部中断通道 4。
 *
 * @return FSP_SUCCESS 表示成功，否则返回错误码
 */
static fsp_err_t external_irq4_init(void)
{
    fsp_err_t err = R_ICU_ExternalIrqOpen(&g_external_irq4_ctrl, &g_external_irq4_cfg);
    if (FSP_SUCCESS != err)
    {
        return err;
    }

    err = R_ICU_ExternalIrqEnable(&g_external_irq4_ctrl);
    return err;
}

/**
 * @brief 根据中断标志更新 LED 输出
 *
 * 根据 s_ext_irq_flag 状态设置指定 IOPORT 引脚高低电平。
 */
static inline void led_update(void)
{
    R_IOPORT_PinWrite(&g_ioport_ctrl,
                      BSP_IO_PORT_01_PIN_04,
                      s_ext_irq_flag ? BSP_IO_LEVEL_HIGH : BSP_IO_LEVEL_LOW);
}


/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    /* 初始化外部中断 IRQ4 */
    fsp_err_t err = external_irq4_init();
    assert(FSP_SUCCESS == err);

    /* 主循环：根据中断事件切换 LED */
    while (1)
    {
        led_update();
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
