#include "hal_data.h"
#include <stdio.h>
FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER


/** @brief 由中断回调函数切换的外部中断标志 */
static volatile bool s_ext_irq_flag = false;

/**
 * @brief 外部中断 IRQ4 回调函数
 *
 * 当 ICU 外部中断发生时调用，切换外部中断标志。
 *
 * @param[in] p_args 中断回调参数（未使用）
 */
void external_irq4_callback(external_irq_callback_args_t *p_args)
{
    (void)p_args;
    s_ext_irq_flag = !s_ext_irq_flag;
}

/**
 * @brief 初始化外部中断 IRQ4
 *
 * 打开并使能 ICU 外部中断通道 4。
 *
 * @return FSP_SUCCESS 表示成功，否则返回错误码
 */
static fsp_err_t external_irq4_init(void)
{
    fsp_err_t err = R_ICU_ExternalIrqOpen(&g_external_irq4_ctrl, &g_external_irq4_cfg);
    if (FSP_SUCCESS != err)
    {
        return err;
    }

    err = R_ICU_ExternalIrqEnable(&g_external_irq4_ctrl);
    return err;
}

/**
 * @brief 根据中断标志更新 LED 输出
 *
 * 根据 s_ext_irq_flag 状态设置指定 IOPORT 引脚高低电平。
 */
static inline void led_update(void)
{
    R_IOPORT_PinWrite(&g_ioport_ctrl,
                      BSP_IO_PORT_01_PIN_04,
                      s_ext_irq_flag ? BSP_IO_LEVEL_HIGH : BSP_IO_LEVEL_LOW);
}

/** @brief PWM 呼吸灯当前占空比计数（0-1000） */
static uint32_t s_pwm_count = 0;
/** @brief PWM 呼吸灯占空比变化方向：true=递增，false=递减 */
static bool s_pwm_increasing = true;

/**
 * @brief 初始化 GPT2 作为 PWM 呼吸灯
 *
 * 配置定时器周期、启动并默认占空比 0。
 * @return FSP_SUCCESS 成功，否则返回错误码
 */
static fsp_err_t pwm_breathe_init(void)
{
    fsp_err_t err = R_GPT_Open(&g_timer2_ctrl, &g_timer2_cfg);
    if (FSP_SUCCESS != err) return err;

    err = R_GPT_PeriodSet(&g_timer2_ctrl, 9000);
    if (FSP_SUCCESS != err) return err;

    /* 启动定时器产生 PWM */
    err = R_GPT_Start(&g_timer2_ctrl);
    if (FSP_SUCCESS != err) return err;

    /* 初始占空比设置为 0（熄灭） */
    return R_GPT_DutyCycleSet(&g_timer2_ctrl, 0, GPT_IO_PIN_GTIOCA);
}

/**
 * @brief 更新 PWM 占空比实现呼吸效果
 *
 * 根据当前计数和方向计算新占空比并写入 GPT。
 */
static void pwm_breathe_update(void)
{
    /* 调整占空比计数 */
    if (s_pwm_increasing)
    {
        s_pwm_count++;
        if (s_pwm_count >= 1000)
        {
            s_pwm_count = 1000;
            s_pwm_increasing = false;
        }
    }
    else
    {
        s_pwm_count--;
        if (s_pwm_count == 0)
        {
            s_pwm_increasing = true;
        }
    }

    /* 设置新的比较值：周期 9000 -> 1% = 90 */
    (void)R_GPT_DutyCycleSet(&g_timer2_ctrl,
                              s_pwm_count * 9,
                              GPT_IO_PIN_GTIOCA);
}

/** @brief UART 发送完成标志 */
volatile bool uart_send_complete_flag = false;
/*******************************************************************************************************************//**
 * @brief UART 发送回调
 *
 * 当 UART 发送完成时调用，置位发送完成标志。
 **********************************************************************************************************************/
void user_uart_callback (uart_callback_args_t * p_args)
{
    if(p_args->event == UART_EVENT_TX_COMPLETE)
    {
        uart_send_complete_flag = true;
    }
}

/*******************************************************************************************************************//**
 * @brief 串口重定向函数
 **********************************************************************************************************************/
#ifdef __GNUC__                                 //串口重定向
    #define PUTCHAR_PROTOTYPE int __io_putchar(int ch)
#else
    #define PUTCHAR_PROTOTYPE int fputc(int ch, FILE *f)
#endif


PUTCHAR_PROTOTYPE
{
    fsp_err_t err = R_SCI_UART_Write(&g_uart9_ctrl, (uint8_t *)&ch, 1);
        if(FSP_SUCCESS != err) __BKPT();
        while(uart_send_complete_flag == false){}
        uart_send_complete_flag = false;
        return ch;
}

int _write(int fd,char *pBuffer,int size)
{
    for(int i=0;i<size;i++)
    {
        __io_putchar(*pBuffer++);
    }
    return size;
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    /* 初始化外部中断 IRQ4 */
    fsp_err_t err = external_irq4_init();
    assert(FSP_SUCCESS == err);

    /* 初始化 PWM 呼吸灯 */
    err = pwm_breathe_init();
    assert(FSP_SUCCESS == err);

    /* 打开 UART9 实例 */
    err = R_SCI_UART_Open(&g_uart9_ctrl, &g_uart9_cfg);
    assert(FSP_SUCCESS == err);

    unsigned char buff[]="RA E2STUDIO";
    uint8_t buff_len = strlen(buff);
    err = R_SCI_UART_Write(&g_uart9_ctrl, buff, buff_len);
    if(FSP_SUCCESS != err) __BKPT();
        while(uart_send_complete_flag == false){}
    uart_send_complete_flag = false;

    printf("\nhello world!\r\n");

    /* 主循环：更新 LED 状态与呼吸效果 */
    while (true)
    {
        led_update();             /* 切换普通 LED */
        pwm_breathe_update();     /* 呼吸灯效果 */
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_MILLISECONDS);
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
